apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ansible-runner-extravars
spec:
  description: Task to write varibles to the ansible runner extravars file
  params:
    - name: vars
      type: array
      description: Array of key=value that will be stored in the extravars file
    - name: image
      type: string
      description: Ansible runner image.
      default: quay.io/ansible/ansible-runner:stable-2.12-latest
  steps:
    - name: create-directory
      image: $(params.image)
      workingDir: $(workspaces.runner-dir.path)
      script: |
        #!/bin/bash
        mkdir -p env
        chmod 777 env
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
    - name: write-extravars-file
      image: $(params.image)
      workingDir: $(workspaces.runner-dir.path)
      args: ["$(params.vars[*])"]
      script: |
        #!/bin/bash
        TARGET_FILE="./env/extravars"

        rm -f ${TARGET_FILE}
        echo "---" >> ${TARGET_FILE}

        for var in "$@"
        do
            IFS='='
            read -a pair <<< "$var"
            echo "${pair[0]}: ${pair[1]}" >> ${TARGET_FILE}
        done
        chmod 666 ${TARGET_FILE}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532

  workspaces:
  - description: The Ansibler runner directory
    name: runner-dir
