apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-autosd-image
spec:
  params:
  - name: playbookGitRepoURL
    description: URL to the git repository of the playbook that should be run.
    type: string
    default: "https://github.com/ygalblum/autosd-build-pipeline.git"
  - name: playbookGitRevision
    description: Git revision of the playbook that should be run.
    type: string
    default: main
  - name: playbookFilename
    description: Filename of the playbook that should be run.
    type: string
    default: playbook.yml
  workspaces:
  - name: ansible
  tasks:
  - name: git-clone
    params:
    - name: url
      value: $(params.playbookGitRepoURL)
    - name: revision
      value: $(params.playbookGitRevision)
    - name: deleteExisting
      value: "true"
    workspaces:
    - name: output
      workspace: ansible
    timeout: 10m
    taskRef:
      kind: ClusterTask
      name: git-clone
  - name: set-extraenv
    params:
    - name: vars
      value:
      - target_namespace="$(context.pipelineRun.namespace)"
      - public_key_secret_name="$(context.pipelineRun.name)-public"
      - private_key_secret_name="$(context.pipelineRun.name)-private"
    taskRef:
      kind: Task
      name: ansible-runner-extravars
    workspaces:
    - name: runner-dir
      workspace: ansible
      subPath: ansible-runner
    runAfter:
    - git-clone
  - name: ansible-runner
    params:
    - name: project-dir
      value: "."
    - name: args
      value:
      - -p
      - $(params.playbookFilename)
    workspaces:
    - name: runner-dir
      workspace: ansible
      subPath: ansible-runner
    runAfter:
    - set-extraenv
    timeout: 1h
    taskRef:
      kind: Task
      name: ansible-runner
