- name: Start the build machine
  hosts: localhost
  gather_facts: false
  vars:
    keypair_name: "id_ssh"
    keypair_path: "/tmp/"
    build_machine_data_source_name: centos-stream9
    build_machine_data_source_namespace: openshift-virtualization-os-images
  tasks:
    - name: Generate the key pair
      community.crypto.openssh_keypair:
        path: "{{keypair_path}}/{{keypair_name}}"
        type: "ed25519"
        force: true
    - name: Save public key as secret
      kubernetes.core.k8s:
        apply: true
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ public_key_secret_name }}"
            namespace: "{{ target_namespace }}"
          type: Opaque
          data:
            id_ed25519.pub: "{{ lookup('file', keypair_path + '/' + keypair_name + '.pub') | b64encode}}"
    - name: Save private key as secret
      kubernetes.core.k8s:
        apply: true
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ private_key_secret_name }}"
            namespace: "{{ target_namespace }}"
          type: Opaque
          data:
            ssh-privatekey: "{{ lookup('file', keypair_path + '/' + keypair_name) | b64encode}}"
    - name: Start the build machine
      kubernetes.core.k8s:
        apply: true
        state: present
        template: templates/vm-template.j2
        wait: true
        wait_condition:
          type: Ready
        wait_timeout: 600
