- name: Start the test machine
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Start the build machine
      kubernetes.core.k8s:
        apply: true
        state: present
        template: templates/vm-template.j2
        wait: true
        wait_condition:
          type: Ready
        wait_timeout: 600
