apiVersion: v1
kind: ServiceAccount
metadata:
  name: autosd-builder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autosd-builder
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "*"
- apiGroups:
  - "kubevirt.io"
  resources:
  - "virtualmachines"
  - "virtualmachineinstances"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autosd-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: autosd-builder
subjects:
- kind: ServiceAccount
  name: autosd-builder
